service: meet-auth-server
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    REDIRECT_URI: ${env:GOOGLE_REDIRECT_URI}
    CALENDAR_ID: ${env:CALENDAR_ID}
  httpApi:
    cors:
      allowedOrigins: ["*"]
      allowedHeaders: [Content-Type]
      allowedMethods: [GET, OPTIONS]

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - httpApi:
          path: /api/get-auth-url
          method: get

  getAccessToken:
    handler: handler.getAccessToken
    events:
      # Path-param route (supports codes with slashes via "+")
      - httpApi:
          path: /api/token/{code+}
          method: get
      # Query-string route: /api/token?code=...
      - httpApi:
          path: /api/token
          method: get

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      # Path-param route (supports tokens with slashes via "+")
      - httpApi:
          path: /api/get-events/{access_token+}
          method: get
      # Query-string route: /api/get-events?access_token=...
      - httpApi:
          path: /api/get-events
          method: get

plugins: []
package:
  individually: false
